---
title: "NIH BD/Finhealth Survey - Descriptive Statistics"
output:
  rmarkdown::github_document:
    html_preview: false
---

```{r class.source='fold-hide', warning=FALSE, message=FALSE}
library(tidyverse)
library(summarytools)
library(dplyr)
library(tidyr)
library(codified)
library(forcats)
library(plyr)
```

## Load data

```{r}
load('data/NIH_survey.Rdata')
```

## Refactor ethnicity towards NIH

```{r}
wide$ethnicity <- revalue(wide$ethnicity, c(
    "Native or Indigenous" = "American Indian/Alaska Native",
    "Asian" = "Asian",
    "Native Hawaiian or Pacific Islanders" = "Native Hawaiian or Other Pacific Islander",
    "Native Hawaiian or Pacific Islanders,White" = "More than One Race",
    "Black/African/Caribbean" = "Black or African American",
    "White" = "White",
    "Native or Indigenous,White" = "More than One Race",
    "Native or Indigenous,Black/African/Caribbean,White" = "More than One Race",
    "Native or Indigenous,Black/African/Caribbean,White,Other" = "More than One Race",
    "Asian,White" = "More than One Race",
    "Asian,White,Other" = "More than One Race",
    "Black/African/Caribbean,White" = "More than One Race",
    "Black/African/Caribbean,Native Hawaiian or Pacific Islanders" = "More than One Race",
    "Native Hawaiian or Pacific Islanders,White,Other" = "More than One Race",
    "White,Other" = "More than One Race",
    "Native or Indigenous,White,Other" = "More than One Race",
    "Native or Indigenous,Asian,Native Hawaiian or Pacific Islanders" = "More than One Race",
    "Native or Indigenous,Black/African/Caribbean" = "More than One Race",
    "Native or Indigenous,Native Hawaiian or Pacific Islanders" = "More than One Race",
    "Native or Indigenous,Asian,White" = "More than One Race",
    "Native or Indigenous,Black/African/Caribbean,Native Hawaiian or Pacific Islanders,White" = "More than One Race",
    "Other" = "Unknown or Not Reported"
  )
)

```

## Demographics Summary

```{r, include=FALSE}
temp <- wide %>% select(gender, age, education, employment, income, marital, ethnicity, hispanic, diagnosis_subtype, hospitalization, PAD, banked, savings, trust_clinician, trust_carepartner, trust_bank)
```

```{r, echo=FALSE}
dfSummary(temp, varnumbers=FALSE, na.col=FALSE, graph.col=FALSE, headings=FALSE)
```
