---
title: "NIH BD/Finhealth Survey - Models"
output:
  rmarkdown::github_document:
    html_preview: false
---

```{r class.source = 'fold-hide', warning=FALSE, message=FALSE}
library(tidyverse)
library(lme4)
library(ordinal)
library(psych)
library(ggthemes)
library(performance)
library(marginaleffects)
library(kableExtra)
library(flextable)
```

## Load data

```{r}
load('data/NIH_survey.Rdata')
```

## Descriptive statistics

### Summary statistics of all variables

```{r, warning=FALSE, message=FALSE}
summary(wide)
```

### Means of outcome for each vignette

```{r, warning=FALSE, message=FALSE}
tab <- long %>% group_by(actors, context, moodstate) %>%
summarize(
          Mean = mean(y, na.rm = TRUE),
          Median = median(y, na.rm = TRUE),
          SD = sd(y, na.rm = TRUE),
          ci = list(mean_cl_normal(y, conf.int = .95)),
          obs = n_distinct(participant)
) %>% unnest(c(ci))
theme_vanilla(flextable(tab)) %>% colformat_double(digits = 2)
```

## Factor analysis

```{r}

# TODO: relevel trust_* as ordered numeric
wide %>% select (trust_carepartner, trust_clinician, trust_bank) %>% mutate_all(scale) %>% fa(., nfactors=1, fm='pa', rotate='varimax')
```

## Modeling

### Unconditional means

```{r}
unconditional.means <- lmer(y ~ 1 + (1|participant) + (1|item), data=long)
summary(unconditional.means)
```

```{r}
performance::icc(unconditional.means, by_group=TRUE)
```

### Primary model

```{r}
m1 <- lmer(y ~ 1 + age + gender + education + ethnicity + hispanic + diagnosis_subtype + hospitalization + banked + savings + trust_clinician + trust_carepartner + trust_bank + cfpb_score + care_partner_help + bfi_agreeableness + (1|participant) + (1|item), data=long)

summary(m1)
```

```{r}
car::Anova(m1, type=3)
```

### Main effects

```{r}

# H1.1: Comfort ratings will be lower during stable periods vs. symptomatic periods
# pairwise test
# m2 is main effects model

m2 <- lmer(y ~ 1 + actors + context + moodstate + (1|participant) + (1|item), data=long)
hypotheses(avg_predictions(m2, by='moodstate', re.form=NULL), 'b2-b1=0')
```

```{r}

# H2.1: Among intervention levels, comfort ratings will be lowest for spending restrictions
# calculate as the difference between an estimate and the mean of all estimates

hypotheses(avg_predictions(m2, by='context', re.form=NULL), 'meandev')
```

```{r}

# H3.1: Comfort will be highest for care partners
# as meandev, like above

hypotheses(avg_predictions(m2, variables='actors', re.form=NULL), multcomp='holm')
```

### Interaction effects

```{r}

# H1.2: Among intervention levels, comfort ratings will be highest for shared spending behaviors during mood episodes
# m3 is interaction between intervention context and mood state

m3 <- lmer(y ~ actors + context * moodstate + (1|participant) + (1|item), data=long)
avg_predictions(m3, by=c('moodstate', 'context'), hypothesis='meandev', re.form=NULL)
plot_predictions(m3, by=c('context', 'moodstate')) + theme_tufte(base_family='sans')
```

```{r}

# H1.3: Among intervention levels, comfort ratings for spending restrictions will be higher during mood episodes vs. during stable periods (H0: 'b2=b5')

avg_predictions(m3, by=c('moodstate', 'context'), hypothesis='b2=b5', re.form=NULL)
plot_predictions(m3, by=c('moodstate', 'context')) + theme_tufte(base_family='sans')
```

### Interaction effects with respondent characteristics

## Additional analysis

```{r}
m4 <- lm(cfpb_score ~ diagnosis_subtype, data=long)
```

```{r}
long$trust_bank <- ordered(long$trust_bank, levels=c('Extremely difficult', 'Somewhat difficult', 'Neither easy nor difficult', 'Somewhat easy', 'Extremely easy'))
long$trust_carepartner <- ordered(long$trust_carepartner, levels=c('Extremely difficult', 'Somewhat difficult', 'Neither easy nor difficult', 'Somewhat easy', 'Extremely easy'))
long$trust_clinician <- ordered(long$trust_clinician, levels=c('Extremely difficult', 'Somewhat difficult', 'Neither easy nor difficult', 'Somewhat easy', 'Extremely easy'))
```
