---
title: "NIH BD/Finhealth Survey - Preprocessing"
output:
  rmarkdown::github_document:
    html_preview: false
---

```{r}
library(tidyverse)
library(plyr)
```

# Preprocessing

## Configure Reticulate for Python use

```{r}
library(reticulate)
conda_create('reticulate') 
use_condaenv('reticulate') 
conda_install('reticulate', 'pandas')
conda_install('reticulate', 'numpy')
```

## Create wide frame

```{r}
qualtrics_data <- read_csv(file='data/Prolific+-+NIH+Survey_March+18,+2024_12.08.csv')
```

```{r}
wide <- 
    tibble(qualtrics_data %>%
        transmute(
            participant = seq.int(nrow(qualtrics_data))-2,
            completed_date = EndDate,
            prolific_id = ProlificID,
            duration = get('Duration (in seconds)'),
            progress = Progress,
            finished = Finished,
            consent = QID1,
            age = Q2,
            gender  = Q3,
            ethnicity = Q4,
            hispanic = Q5,
            state = Q118,
            regionality = Q7,
            diagnosis_tf = Q10,
            diagnosis_subtype = Q11,
            diagnosis_age = Q126,
            hospitalization = Q153,
            PAD = Q145,
            marital = Q8,
            education = Q9,
            employment = Q12,
            income = Q80,
            banked = Q14,
            savings = Q124,
            pay_later_service = Q246,
            main_financial_goal = Q122,
            bankruptcy_declared = Q56,
            bankruptcy_considered = Q57,
            care_partner_help = Q60,
            collaborative_strategies = Q61,
            collaborative_strat_appr_1 = Q128_1,
            collaborative_strat_appr_2 = Q128_2,
            collaborative_strat_appr_3 = Q128_3, 
            collaborative_strat_appr_4 = Q128_4,
            collaborative_strat_appr_5 = Q128_5,
            collaborative_strat_appr_6 = Q128_6,
            care_partner_feelings_1 = Q136_1,
            care_partner_feelings_2 = Q136_2,
            care_partner_feelings_3 = Q136_3,
            care_partner_feelings_4 = Q136_4,
            care_partner_feelings_5 = Q136_5,
            care_partner_feelings_6 = Q136_6,
            care_partner_no_collab_1 = Q137_1,
            care_partner_no_collab_2 = Q137_2,
            care_partner_no_collab_3 = Q137_3,
            care_partner_no_collab_4 = Q137_4,
            care_partner_no_collab_5 = Q137_5,
            care_partner_no_collab_6 = Q137_6,
            conflict_mitigation = Q155,
            trust_clinician = Q157_1,
            trust_bank = Q157_2,
            trust_carepartner = Q157_3,
            cfpb_1 = Q138_1,
            cfpb_2 = Q138_2,
            cfpb_3 = Q138_3,
            cfpb_4 = Q139_1,
            cfpb_5 = Q139_2,
            bfi_1_reserved = Q119_1,
            bfi_2_trusting = Q119_2,
            bfi_3_lazy = Q119_3,
            bfi_4_relaxed = Q119_4,
            bfi_5_few_artistic = Q119_5,
            bfi_6_outgoing = Q119_6,
            bfi_7_fault = Q119_7,
            bfi_8_thorough = Q119_8,
            bfi_9_nervous = Q119_9,
            bfi_10_imagination = Q119_10,
            # pattern is item.displayblock.actor.context.moodstate
            v1.understand_behavior.clinicians.share_spending.mood = Q351_1,    # vignette 1
            v2.understand_behavior.clinicians.share_spending.stable = Q353_1,  # vignette 2
            v3.understand_behavior.carepartner.share_spending.mood = Q354_1,   # vignette 3
            v4.understand_behavior.carepartner.share_spending.stable = Q356_1, # vignette 4
            v5.understand_behavior.banks.share_spending.mood = Q357_1,         # vignette 5
            v6.understand_behavior.banks.share_spending.stable = Q359_1,       # vignette 6
            v7.budgeting.clinicians.planning_budgeting.mood = Q387_1,          # vignette 7
            v8.budgeting.clinicians.planning_budgeting.stable = Q389_1,        # vignette 8
            v9.budgeting.carepartner.planning_budgeting.mood = Q390_1,         # vignette 9
            v10.budgeting.carepartner.planning_budgeting.stable = Q392_1,     # vignette 10
            v11.budgeting.banks.planning_budgeting.mood = Q393_1,             # vignette 11
            v12.budgeting.banks.planning_budgeting.stable = Q395_1,           # vignette 12
            v13.restrict.clinicians.restrict_spending_48.mood = Q396_1,       # vignette 13
            v14.restrict.clinicians.restrict_spending_48.stable = Q398_1,     # vignette 14
            v15.restrict.carepartner.restrict_spending_48.mood = Q399_1,      # vignette 15
            v16.restrict.carepartner.restrict_spending_48.stable = Q401_1,    # vignette 16
            v17.restrict.banks.restrict_spending_48.mood = Q402_1,            # vignette 17
            v18.restrict.banks.restrict_spending_48.stable = Q404_1,          # vignette 18
        ) %>%
        filter(!row_number() %in% c(0:2)) %>%
        mutate(
            across(c(
                age, 
                gender, 
                ethnicity, 
                hispanic,
                state,
                regionality,
                diagnosis_tf, 
                diagnosis_subtype,
                diagnosis_age,
                hospitalization,
                PAD,
                marital,
                education,
                employment,
                income,
                banked,
                savings,
                pay_later_service,
                main_financial_goal,
                bankruptcy_declared,
                bankruptcy_considered,
                care_partner_help,
                collaborative_strategies,
                collaborative_strat_appr_1,
                collaborative_strat_appr_2,
                collaborative_strat_appr_3, 
                collaborative_strat_appr_4,
                collaborative_strat_appr_5,
                collaborative_strat_appr_6,
                care_partner_feelings_1,
                care_partner_feelings_2,
                care_partner_feelings_3,
                care_partner_feelings_4,
                care_partner_feelings_5,
                care_partner_feelings_6,
                care_partner_no_collab_1,
                care_partner_no_collab_2,
                care_partner_no_collab_3,
                care_partner_no_collab_4,
                care_partner_no_collab_5,
                care_partner_no_collab_6,
                conflict_mitigation,
                trust_clinician,
                trust_bank,
                trust_carepartner
                ), factor)
        ) %>%
        mutate(
          across(c(
            completed_date
          ), ~format(as.POSIXct(., format = "%m/%d/%Y %H:%M"), "%m/%d/%Y %H:%M"))
        )
    )
```

## Refactor ethnicity towards NIH requirements

```{r}
wide$ethnicity <- revalue(wide$ethnicity, c(
    "Native or Indigenous" = "American Indian/Alaska Native",
    "Asian" = "Asian",
    "Native Hawaiian or Pacific Islanders" = "Native Hawaiian or Other Pacific Islander",
    "Native Hawaiian or Pacific Islanders,White" = "More than One Race",
    "Black/African/Caribbean" = "Black or African American",
    "White" = "White",
    "Native or Indigenous,White" = "More than One Race",
    "Native or Indigenous,Black/African/Caribbean,White" = "More than One Race",
    "Native or Indigenous,Black/African/Caribbean,White,Other" = "More than One Race",
    "Asian,White" = "More than One Race",
    "Asian,White,Other" = "More than One Race",
    "Black/African/Caribbean,White" = "More than One Race",
    "Black/African/Caribbean,Native Hawaiian or Pacific Islanders" = "More than One Race",
    "Native Hawaiian or Pacific Islanders,White,Other" = "More than One Race",
    "White,Other" = "More than One Race",
    "Native or Indigenous,White,Other" = "More than One Race",
    "Native or Indigenous,Asian,Native Hawaiian or Pacific Islanders" = "More than One Race",
    "Native or Indigenous,Black/African/Caribbean" = "More than One Race",
    "Native or Indigenous,Native Hawaiian or Pacific Islanders" = "More than One Race",
    "Native or Indigenous,Asian,White" = "More than One Race",
    "Native or Indigenous,Black/African/Caribbean,Native Hawaiian or Pacific Islanders,White" = "More than One Race",
    "Other" = "Unknown or Not Reported"
  )
)

```

## Account for survey duration

```{r}
wide$speeder <- ifelse(as.numeric(wide$duration) < 0.6*median(as.numeric(wide$duration)),
+        1,
+        0)
```

## Merge Qualtrics with Prolific demographics, NIH GUIDs

```{python}
import pandas as pd
demog = pd.read_csv('data/prolific_demographic_export.csv')
pguids = pd.read_csv('data/pguids.csv', usecols=['PseudoGUID'])

# remove duplicate rows, keeping 'last' to preserve responses
df_int = r.wide.drop_duplicates(subset='prolific_id', keep='last')

# include only those participants that were approved (and paid) within Prolific
demog = demog.loc[(demog.Status == 'APPROVED')].drop_duplicates()

# create master dataframes
# merge prolific demographic export (n=500) with qualtrics exports, joining on prolific ID
# fix internal participant IDs (float -> int)
qual_int = demog.merge(df_int, left_on='Participant id', right_on='prolific_id', how='left').drop_duplicates(subset='Participant id', keep='last')
qual_int['participant'] = qual_int['participant'].astype('int')

# add NIMH NDA pseudoGUIDs
qual_int.insert(loc=0, column='pguid', value=pguids)
```

## Score CFPB with CFPB_5 reverse-coded

```{python}
# score CFPB with CFPB_5 reverse-coded
qual_int[['cfpb_1', 'cfpb_2', 'cfpb_3', 'cfpb_4', 'cfpb_5']] = qual_int[['cfpb_1', 'cfpb_2', 'cfpb_3', 'cfpb_4', 'cfpb_5']].fillna(0).astype('int')
qual_int['cfpb_5'] = 5 - qual_int['cfpb_5']

# CFPB scores vary by age, so create indicator var using pd.loc()
qual_int.Age = qual_int.Age.astype('int')
qual_int.loc[(qual_int.Age > 61), 'cfpb_age_group'] = 0
qual_int.loc[(qual_int.Age >= 18) & (qual_int.Age <= 61), 'cfpb_age_group'] = 1
cfpb_scoring_age18_61 = {0: 19, 1: 25, 2: 29, 3: 32, 4: 36, 5: 38, 6: 41, 7: 43, 8: 46, 9: 48, 10: 50, 11: 53, 12: 55, 13: 57, 14: 60, 15: 63, 16: 65, 17: 68, 18: 72, 19: 76, 20: 82}
cfpb_scoring_age62    = {0: 20, 1: 26, 2: 31, 3: 34, 4: 37, 5: 40, 6: 43, 7: 46, 8: 48, 9: 51, 10: 53, 11: 55, 12: 58, 13: 61, 14: 63, 15: 66, 16: 69, 17: 73, 18: 76, 19: 81, 20: 90}

# calculate CFPB scores based on age group
cfpb_scores_1 = qual_int.loc[qual_int['cfpb_age_group'] == 1][['cfpb_1', 'cfpb_2', 'cfpb_3', 'cfpb_4', 'cfpb_5']].sum(axis=1).replace(cfpb_scoring_age18_61)
cfpb_scores_0 = qual_int.loc[qual_int['cfpb_age_group'] == 0][['cfpb_1', 'cfpb_2', 'cfpb_3', 'cfpb_4', 'cfpb_5']].sum(axis=1).replace(cfpb_scoring_age62)

qual_int['cfpb_score'] = pd.concat([cfpb_scores_1, cfpb_scores_0]).sort_index()
```

### Score BFI10

```{python}

import statistics as stat

# convert BFI datatype to int
qual_int[['bfi_1_reserved' ,'bfi_2_trusting', 'bfi_3_lazy','bfi_4_relaxed', 'bfi_5_few_artistic', 'bfi_6_outgoing', 'bfi_7_fault', 'bfi_8_thorough', 'bfi_9_nervous', 'bfi_10_imagination']] = qual_int[['bfi_1_reserved' ,'bfi_2_trusting', 'bfi_3_lazy','bfi_4_relaxed', 'bfi_5_few_artistic', 'bfi_6_outgoing', 'bfi_7_fault', 'bfi_8_thorough', 'bfi_9_nervous', 'bfi_10_imagination']].fillna(0).astype('int')

# BFI10 scoring, where R is reverse coded (6 - response value)
# Extraversion: 1R, 5
# Agreeableness: 2, 7R
# Conscientiousness: 3R, 8
# Neuroticism: 4R, 9
# Openness to Experience: 5R, 10

qual_int['bfi_extraversion'] = ((6-qual_int['bfi_1_reserved']) + (qual_int['bfi_5_few_artistic']) / 2)
qual_int['bfi_agreeableness'] = ((qual_int['bfi_2_trusting']) + (6-qual_int['bfi_7_fault']) / 2)
qual_int['bfi_conscientiousness'] = ((6-qual_int['bfi_3_lazy'] + qual_int['bfi_8_thorough']) / 2)
qual_int['bfi_neuroticism'] = ((6-qual_int['bfi_4_relaxed']) + (qual_int['bfi_9_nervous']) / 2)
qual_int['bfi_openness'] = ((6-qual_int['bfi_5_few_artistic']) + (qual_int['bfi_10_imagination']) / 2)
```

# Create long frame

```{r}

wide <- py$qual_int

# pivot from wide to long with vignette rating as outcome var
long <- py$qual_int %>%
    pivot_longer(
        cols = c('v18.restrict.banks.restrict_spending_48.stable',
                'v17.restrict.banks.restrict_spending_48.mood',
                'v16.restrict.carepartner.restrict_spending_48.stable',
                'v15.restrict.carepartner.restrict_spending_48.mood',
                'v14.restrict.clinicians.restrict_spending_48.stable',
                'v13.restrict.clinicians.restrict_spending_48.mood',
                'v12.budgeting.banks.planning_budgeting.stable',
                'v11.budgeting.banks.planning_budgeting.mood',
                'v10.budgeting.carepartner.planning_budgeting.stable',
                'v9.budgeting.carepartner.planning_budgeting.mood',
                'v8.budgeting.clinicians.planning_budgeting.stable',
                'v7.budgeting.clinicians.planning_budgeting.mood',
                'v6.understand_behavior.banks.share_spending.stable',
                'v5.understand_behavior.banks.share_spending.mood',
                'v4.understand_behavior.carepartner.share_spending.stable',
                'v3.understand_behavior.carepartner.share_spending.mood',
                'v2.understand_behavior.clinicians.share_spending.stable',
                'v1.understand_behavior.clinicians.share_spending.mood'),
            names_to = c('item', 'block', 'actors', 'context', 'moodstate'),
            names_sep = '\\.',
            names_repair = 'minimal',
            values_to = 'y'
    ) %>%
    mutate(
        across(c(item, block, actors, context, moodstate), factor),
        y = as.numeric(y),
        actors = recode(actors, "carepartner" = "Care Partner", "banks" = "Banks", "clinicians" = "Clinicians"),
        context = recode(
          context, "share_spending" = "Share Spending Details", "planning_budgeting" = "Help with Planning & Budgeting", "restrict_spending_48" = "48-hour Spending Restriction"),
        moodstate = recode(moodstate, "mood" = "Symptomatic", "stable" = "Euthymic")
    )
```

```{r}
save(wide, long, file='data/NIH_survey.Rdata')
write.csv(wide, "data/NIH_survey_wide.csv")
write.csv(long, "data/NIH_survey_long.csv")
```

# Data quality checks

## Test demographic dependencies

```{r}
chisq.test(table(long$age, long$y), simulate.p.value =T)
chisq.test(table(long$gender, long$y), simulate.p.value =T)
chisq.test(table(long$marital, long$y), simulate.p.value =T)
chisq.test(table(long$ethnicity, long$y), simulate.p.value =T)
chisq.test(table(long$education, long$y), simulate.p.value =T)
chisq.test(table(long$employment, long$y), simulate.p.value =T)
```

```{r}
fisher.test(table(long$ethnicity, long$y), simulate.p.value = TRUE)
```
