---
title: "NIH BD/Finhealth Survey - Descriptive Statistics"
output:
  rmarkdown::github_document:
    html_preview: false
---

```{r class.source='fold-hide', warning=FALSE, message=FALSE}
install.packages("pacman", repos = "https://cloud.r-project.org")
pacman::p_load("tidyverse", "summarytools", "dplyr", "tidyr", "codified", "forcats", "plyr", "janitor")
```

## Load data

```{r}
load('data/NIH_survey.Rdata')
```

## Demographics Summary

```{r, include=FALSE}
temp <- wide %>% select(gender, age, education, employment, income, main_financial_goal, pay_later_service, marital, ethnicity, hispanic, diagnosis_subtype, diagnosis_age, hospitalization, PAD, banked, savings, bankruptcy_declared, bankruptcy_considered, care_partner_help, trust_clinician, trust_carepartner, trust_bank)

temp <- temp %>% 
  dplyr::rename(
    Gender = gender,
    Age = age,
    Education = education,
    `Employment Status` = employment,    # Use backticks for names with spaces
    `Income Level` = income,
    `Main Financial Goal` = main_financial_goal,
    `Has used Pay Later Services` = pay_later_service,
    `Marital Status` = marital,
    Ethnicity = ethnicity,
    Hispanic = hispanic,
    `Bipolar Subtype` = diagnosis_subtype,
    `Prior Hospitalization` = hospitalization,
    `Is Banked` = banked,
    `Has Savings Account` = savings,
    `Bankruptcy Declared` = bankruptcy_declared,
    `Bankruptcy Considered` = bankruptcy_considered,
    `Requested Financial Help from Care Partner` = care_partner_help,
    `Age at Diagnosis` = diagnosis_age,
    `Has Psychiatric Advance Directive` = PAD,
    `Ease in Trusting Clinicians` = trust_clinician,
    `Ease in Trusting Care Partner` = trust_carepartner,
    `Ease in Trusting Banks` = trust_bank
  )
```

```{r, echo=FALSE}
view(dfSummary(temp, varnumbers=FALSE, na.col=FALSE, graph.col=FALSE, headings=FALSE, valid.col=FALSE, style='grid', plain.ascii=FALSE), file='tables/tbl-demographics.md')
```

## Create descriptive plots

```{r}

library(ggplot2)
library(scales)

wide %>% 
  drop_na(main_financial_goal) %>%
  ggplot(aes(x = after_stat(prop), group=1, y = forcats::fct_infreq(main_financial_goal))) +
  geom_bar(stat = "count", width=.65) +
  scale_x_continuous(labels = scales::percent) +
  scale_y_discrete(labels = label_wrap(width=38), limits = rev(levels(forcats::fct_infreq(wide$main_financial_goal)))) + 
  labs(y = "Main Financial Goal",
       x = "Percentage of Respondents") +
  theme_light(base_family='Lato', base_size=16) 

ggsave('plots/desc_main_financial_goal.png', width=9, height=6, dpi=600)
ggsave('plots/desc_main_financial_goal.eps', device='eps', width=9, height=6, dpi=600)
```